### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Nivekiba** [brettlangdon/importhook#1]
Hello @brettlangdon , i'm working with python 2 and your module is giving out some errors

while in python 3 there are no errors

**Comment by brettlangdon** [comment]
@Nivekiba would you be willing to share the errors you are seeing with an example of how you are using the library?

**Comment by Nivekiba** [comment]
After typing ```python -i intercept.py``` (python)

i got the following errors:

![image](https://user-images.githubusercontent.com/20845649/76238500-38da3c00-6230-11ea-88c4-ecbb3d92bd0a.png)

In the `intercept.py` it's just a simple `print function`

**Comment by Nivekiba** [comment]
Why ?

**Comment by Nivekiba** [comment]
![image](https://user-images.githubusercontent.com/20845649/76240119-f7975b80-6232-11ea-8550-74fb1d1814e3.png)

This is the other error i'm getting

**Comment by brettlangdon** [comment]
I just released `1.0.7`, please give that a try and let me know if the issue still exists.

The problem is because I was using f-strings for logging instead of `''.format()`

I'd prefer to maintain this library only for Python 3, but this is an easy enough change to get this working.

**Comment by Nivekiba** [comment]
And for the errors on `importlib.abc` ?
Is there anyway to avoid that ?

**Comment by brettlangdon** [comment]
yeah, I am going to update this package so it won't install on Python 2, that was my original intention anyways.

I am sorry about any confusion here, I put the package metadata as Python 3 only, but I should have done `python_requires=">3.3"`.

I am only interested in maintaining this package for Python 3 since Python 2 is now EOL.
