### ISSUE TITLE
Invalid super call in HookMetaPaths.__setitem__()?

### ISSUE THREAD

**Issue by akaihola** [brettlangdon/importhook#2]
Reading through the code of this interesting package, I noticed this in the `HookMetaPaths` class:

```python
    def __setitem__(self, key, val):
        super(HookMetaPaths, self).__setitem__(hook_finder(val))
```

Shouldn't the arguments of the super call be `__setitem__(key, hook_finder(val))` instead?

**Comment by brettlangdon** [comment]
hmm, not sure how I missed that, want to put up a PR for it? otherwise I can try to fix later today.

also probably goes to show that I need to add more tests :D

**Comment by akaihola** [comment]
I can do a PR if you like but unfortunately I'm still busy today and tomorrow (European time zone).
