### ISSUE TITLE
Import location

### ISSUE THREAD

**Issue by wackazong** [brettlangdon/importhook#5]
Is it possible to get the path where the module is about to be imported?

**Comment by brettlangdon** [comment]
@wackazong this module will only notify you _after_ the module is imported.

If you want to monitor and react _before_ a module is imported, you can take a look at [PEP 578](https://www.python.org/dev/peps/pep-0578/) which introduces [sys.audit](https://docs.python.org/3/library/sys.html#sys.audit)/[sys.addaudithook](https://docs.python.org/3/library/sys.html#sys.addaudithook). (Python 3.8+)

This new API also introduces an `import` audit event.


API Function | Event Name | Arguments | Rationale
-- | -- | -- | --
import | import | (module, filename, sys.path, sys.meta_path, sys.path_hooks) | Detect when modules are imported. This is raised before the module name is resolved to a file. All arguments other than the module name may be None if they are not used or available.


```python
import sys


def audit_hook(event, args):
    # Ignore all events except for "import"
    if event != "import":
        return

    module, filename, path, meta_path, path_hooks = args
    # Do something here, raising an exception will prevent the module from being imported


sys.addaudithook(audit_hook)
```

**Comment by wackazong** [comment]
Ok, thanks.
